### ISSUE TITLE
Are RCODE kernel_ver_msg and repository_msg used after startup?

### ISSUE THREAD

**Issue by ecm-pushbx** [SvarDOS/edrdos#103]
These two messages are part of drbio. They appear to be resident in the HMA with `dos=high`. https://github.com/SvarDOS/edrdos/blob/525b418819b1c775afd040f28c0254fb527646ae/drbio/biosmsgs.asm

Should they be moved to an init-only section?

In lDOS EDR-DOS this currently includes starting_dos_msg and drdosprojects_msg: https://hg.pushbx.org/ecm/edrdos/file/3fe7cd41cc10/drbio/biosmsgs.asm

What happened to starting_dos_msg in SvarDOS EDR-DOS? Did it get deleted entirely?

**Comment by boeckmann** [comment]
I fiddled around with this trying to make the kernel message more similar to the FreeDOS one, getting in the git revision etc. starting_dos_msg is removed because the kernel msg should be sufficient to show "that the kernel is there". I am afraid the lDOS custumizations were lost in this process, but I will re-include them.

Regarding RCODE, I think someone wanted to have these strings in memory all the time? Could probably relocated to some other segment...

**Comment by ecm-pushbx** [comment]
> I fiddled around with this trying to make the kernel message more similar to the FreeDOS one, getting in the git revision etc. starting_dos_msg is removed because the kernel msg should be sufficient to show "that the kernel is there". I am afraid the lDOS custumizations were lost in this process, but I will re-include them.

That explains the lack of the starting message.

> Regarding RCODE, I think someone wanted to have these strings in memory all the time? Could probably relocated to some other segment...

I don't think we should waste this space if there is no interface to query these at runtime.

**Comment by boeckmann** [comment]
Yes I agree. We could put it directly in INITCODE in init.asm. Should work...

**Comment by boeckmann** [comment]
INITDATA, I meant

**Comment by ecm-pushbx** [comment]
Fixed in https://github.com/SvarDOS/edrdos/commit/e09bc11c0ddb71ff8e34740373545d4f6b248d14 and picked into https://hg.pushbx.org/ecm/edrdos/rev/e637d5e1cb0c
