### ISSUE TITLE
unable to find COMMAND.COM when booting from secondary disk + wrong current drive set

### ISSUE THREAD

**Issue by mateuszviste** [SvarDOS/edrdos#111]
I configured a VBox VM with an empty (no partitions) disk. Then I attached the SvarDOS USB bootable image as a secondary (slave) disk. Instructed VBox to boot from the secondary disk (through the F12 key for the VBox boot selection menu). Result:

![image](https://github.com/user-attachments/assets/4269e1d0-6f9f-47fd-ac90-faf3c2cf0dd6)

I do not know how to interpret the warning. It seems that while EDR booted from the secondary disk, it looks for a partition on the primary disk (which has none).

What happens next is probably a consequence of the above. EDR says he cannot find COMMAND.COM. I tell it to load it from "C:\COMMAND.COM" and then it finds it. BUT it sets the default (current) drive to be "D:", which is a drive that does not exists... If I switch to C: manually then everything works. FDISK /info report:

![image](https://github.com/user-attachments/assets/afb8a5da-7e15-44f6-90c3-b29af083091f)

**Comment by ecm-pushbx** [comment]
As a preliminary check you could install testboot from https://github.com/SvarDOS/edrdos/issues/102#issuecomment-2306915415 into the partition boot sector (`instsect C: /s=testboot.bin /sn`) and particularly check what `dl` value you get.

**Comment by mateuszviste** [comment]
used test12.bin instead of testboot.bin:

![image](https://github.com/user-attachments/assets/a39835fe-556c-4dea-9ab4-9ccfd9e4fc2f)

then, after reboot:

![image](https://github.com/user-attachments/assets/5662dc57-acdf-4bcc-9536-637d0d70911f)

So... DL=0x81. Yet EDR seems to be looking for the boot partition on the first drive (0x80).

**Comment by boeckmann** [comment]
I have an idea what causes this. As DL is 81 init_drv gets set to 3. But from EDR perspective there is no logical drive 3, because the first disk contains no partition. Therefore the "warning: can't find boot partition". On the machine I currently test the disks get swapped by the BIOS, so second drive becomes 0x80. This prevents the problem. I may have to install VirtualBox to reproduce this.

https://github.com/SvarDOS/edrdos/blob/e62ca5db79db138ca656ec5760ea27816640fafd/drbio/init.asm#L948-L954

init_drv will be set to 3 in your case, but the following the condition in line 669 will probably evaluate to true, causing a problem:

https://github.com/SvarDOS/edrdos/blob/e62ca5db79db138ca656ec5760ea27816640fafd/drbio/config.asm#L664-L673

So I guess, my recent change to change init_drv not being hardcoded to 2 may have had bad side-effects. It is probably better to leave this at 2 and let do `detect_boot_drv` do the rest. With ECMs change to verify the physical drive number this should be safe.

**Comment by boeckmann** [comment]
QEMU BIOS also seems to renumber the drives, or it works for some other reason. So until now no success in reproducing. Will try with VirtualBox in the afternoon...

**Comment by mateuszviste** [comment]
> QEMU BIOS also seems to renumber the drives, or it works for some other reason. So until now no success in reproducing. Will try with VirtualBox in the afternoon...

Yes, qemu "cheats" and reorders disks when asked to boot from the secondary one (my primary appears then in FDISK /info 2). VBox does not do that.

**Comment by boeckmann** [comment]
Was able to reproduce under QEMU with lDebug and booting via
```
boot hdb
g
```

I changed https://github.com/SvarDOS/edrdos/blob/e62ca5db79db138ca656ec5760ea27816640fafd/drbio/init.asm#L952

to `mov al,2`. It now seems to work. It also works if the first disk contains a partition. The partition is then D:, and the kernel correctly detects this. Will make a push shortly...

**Comment by ecm-pushbx** [comment]
I was about to suggest booting lDebug off fda and running `boot hdb`. MetaKern also has an option to boot off what it calls "D:" I think.

Picked into https://hg.pushbx.org/ecm/edrdos/rev/1192143fcfc3
