### ISSUE TITLE
[Patch] LBA access broken since 2024 March revision (ecm repo)

### ISSUE THREAD

**Issue by ecm-pushbx** [SvarDOS/edrdos#60]
Details on the bug and fix: http://www.bttr-software.de/forum/forum_entry.php?id=21854&page=0&category=0&order=last_answer

**Comment by boeckmann** [comment]
Damn, too bad that one slipped me through. Thanks for the patch. Will merge it on weekend.

**Comment by boeckmann** [comment]
Reminder to myself: there are other places that might be problematic and should be investigated:

https://github.com/SvarDOS/edrdos/blob/082f60b24c0da9f9c9f588ab1e8f2255bf7890a2/drbio/disk.asm#L627

ioctl:
https://github.com/SvarDOS/edrdos/blob/082f60b24c0da9f9c9f588ab1e8f2255bf7890a2/drbio/disk.asm#L1586
https://github.com/SvarDOS/edrdos/blob/082f60b24c0da9f9c9f588ab1e8f2255bf7890a2/drbio/disk.asm#L1645
https://github.com/SvarDOS/edrdos/blob/082f60b24c0da9f9c9f588ab1e8f2255bf7890a2/drbio/disk.asm#L1647

**Comment by boeckmann** [comment]
Letting the user alter the LBA setting via ioctl set is probably not such a good idea, because this could be done by accident if software calls ioctl set with bitmasked values returned by a previous ioctl get (if the programmer did not expect UDF_LBA to be set).

Returning it should be safe though and may be useful to find out if the kernel accesses the disk via LBA.
